---
title: "Journals Sentiment Analysis"
author: "Graham Hamblin"
output:
  html_document:  
    theme: readable
    code_folding: hide
    fig_align: 'center'
---

```{r load_libraries, include=FALSE}

library(tidyverse)
library(lubridate)
library(data.table)
library(ggplot2)

```

```{r load_data}

journals_raw <- read_csv("../../derived_data/journal_sentiments.csv")

events_raw <- read_csv("significant_events.csv")

```

```{r tidy_data}

journals <- journals_raw %>%
  mutate(date = as.Date(date, format="%B %d, %Y")) %>%
  filter(sentiment != 0) %>%
  na.omit() # drops two rows (invalid dates)

journals

```

```{r fig.height=5, fig.width=20}

plot <- ggplot(journals, aes(x = date, y = sentiment)) + 
          # geom_point(size = 0.001) + 
          geom_smooth(
            method = 'loess', 
            formula = y ~ x, 
            se = FALSE, 
            span = 0.05, 
            color = 'black')

```

```{r}

fit_smooth <- function(date) {
  
  # prep data
  gg_data <- ggplot_build(plot)$data %>%
    as.data.frame() %>%
    mutate(distance = x - as.numeric(date)) %>%
    select(x, y, distance)
  
  # get closest points to left
  below <- filter(gg_data, distance < 0)
  p0 <- below[which.max(below$distance),]
  
  # get closest point to right
  above <- filter(gg_data, distance > 0)
  p1 <- above[which.min(above$distance),]
  
  # get point to left
  x0 <- p0$x
  y0 <- p0$y
  
  # get point to right
  x1 <- p1$x
  y1 <- p1$y
  
  # calculate change in y versus (x0, y0)
  slope <- (y1 - y0) / (x1 - x0)
  dx <- as.numeric(date) - x0
  dy <- y0 + (dx * slope)
  
  # adjust y-value
  y <- y0 + dy
  
  return(y)
  
}

```

```{r}

events <- events_raw %>%
  mutate(
    date = as.Date(date, format="%d %B %Y"), 
    y = fit_smooth(date))

events

```

```{r fig.height=5, fig.width=20}

plot + 
  geom_point(data = events, 
             aes(x = date, y = y), 
             size = 3, color = 'red') + 
  labs(title = "Sentiment of Wilford Woodruff\'s Journal Entries",
       x = '', 
       y = "Sentiment") + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5, size = 25))

```
